return
{
	-- 把歌曲文件放在 zsound 文件夹中 , 要求是 ogg 或 wav 格式
	-- 格式【{ "名称" , "文件名包括后缀名" , 音量 } ,】
	--
	-- "名称" 不能是空的 , 也不能重复
	-- "名称" 和 "文件名包括后缀名" 支持中文
	--
	-- 如果歌曲文件放在 zsound 文件夹中的子文件夹内 , 则 "文件名包括后缀名" 这一项要带上子文件夹的名称 , 栗如 : "new/bgm.ogg"
	-- 同样的 , 子文件夹名称也支持中文
	--
	-- 音量 1 表示 100% , 而 0.1 则表示 10%
	-- 音量可以不写 , 默认为 1
	--
	-- 例子 :
	-- { "主题曲" , "曲子1.wav" , 0.9 } ,
	-- { "测试音乐" , "测试文件夹/测试音乐.ogg" , 0.5 } ,
	-- { "插曲" , "曲子2.ogg" ,  } ,
	-- { "music1" , "music11111.ogg" , 0.01 } ,
	
	{ "wwww-Bunny Panic!!!" , "音乐待寻找/wwww-Bunny Panic!!!.ogg" , 1 } ,
	{ "wwww-doll" , "音乐待寻找/wwww-doll.ogg" , 1 } ,
	{ "wwww-explosion 爆炸 古典辣妹" , "音乐待寻找/wwww-explosion 爆炸 古典辣妹.ogg" , 1 } ,
	{ "wwww-Growing!" , "音乐待寻找/wwww-Growing!.ogg" , 1 } ,
	{ "wwww-Hot Limit-T.M.Revolution-加快版" , "音乐待寻找/wwww-Hot Limit-T.M.Revolution-加快版.ogg" , 1 } ,
	{ "wwww-INSIDE IDENTITY" , "音乐待寻找/wwww-INSIDE IDENTITY.ogg" , 1 } ,
	{ "wwww-RUN! RUN! RUN!" , "音乐待寻找/wwww-RUN! RUN! RUN!.ogg" , 1 } ,
	{ "wwww-UNITY" , "音乐待寻找/wwww-UNITY.ogg" , 1 } ,
	{ "wwww-Van!shment Th!s World" , "音乐待寻找/wwww-Van!shment Th!s World.ogg" , 1 } ,
	{ "wwww-オレンジ" , "音乐待寻找/wwww-オレンジ.ogg" , 1 } ,
	{ "wwww-初音未来-天威咫尺" , "音乐待寻找/wwww-初音未来-天威咫尺.ogg" , 1 } ,
	{ "wwww-千と千尋の神隠しいつも何度でも feat. Chieko Kinbara" , "音乐待寻找/wwww-千と千尋の神隠しいつも何度でも feat. Chieko Kinbara.ogg" , 1 } ,
	{ "wwww-变态震动" , "音乐待寻找/wwww-变态震动.ogg" , 1 } ,
	{ "wwww-廃獄ララバイ·改" , "音乐待寻找/wwww-廃獄ララバイ·改.ogg" , 1 } ,
	{ "wwww-德丽莎的teriteri循环（语音madcv：田村ゆかり）" , "音乐待寻找/wwww-德丽莎的teriteri循环（语音madcv：田村ゆかり）.ogg" , 1 } ,
	{ "wwww-曲目 11" , "音乐待寻找/wwww-曲目 11.ogg" , 1 } ,
	{ "wwww-机巧少女不会受伤OP" , "音乐待寻找/wwww-机巧少女不会受伤OP.ogg" , 1 } ,
	{ "wwww-海贼王 - op2" , "音乐待寻找/wwww-海贼王 - op2.ogg" , 1 } ,
	{ "wwww-漆黒に躍る弧濁覇王節(『中二病也要谈恋爱 Lite』ED主题曲)" , "音乐待寻找/wwww-漆黒に躍る弧濁覇王節(『中二病也要谈恋爱 Lite』ED主题曲).ogg" , 1 } ,
	{ "wwww-舞-HiME.Mai.Hime.OST.Vol.1.姬" , "音乐待寻找/wwww-舞-HiME.Mai.Hime.OST.Vol.1.姬.ogg" , 1 } ,
	{ "wwww-蓬莱伝説" , "音乐待寻找/wwww-蓬莱伝説.ogg" , 1 } ,
	{ "wwww-霊知の太阳信仰 ～ Nuclear Fusi" , "音乐待寻找/wwww-霊知の太阳信仰 ～ Nuclear Fusi.ogg" , 1 } ,
	{ "wwww-青空のラプソディ" , "音乐待寻找/wwww-青空のラプソディ.ogg" , 1 } ,
	{ "wwww-風神少女" , "音乐待寻找/wwww-風神少女.ogg" , 1 } ,
	{ "yyyy-Flower Dance" , "音乐待寻找/yyyy-Flower Dance.ogg" , 1 } ,
	{ "yyyy-GIVE　ME　FIVE" , "音乐待寻找/yyyy-GIVE　ME　FIVE.ogg" , 1 } ,
	{ "yyyy-Orange-Claris" , "音乐待寻找/yyyy-Orange-Claris.ogg" , 1 } ,
	{ "yyyy-不安定な神様" , "音乐待寻找/yyyy-不安定な神様.ogg" , 1 } ,
	{ "yyyy-你-屠洪纲" , "音乐待寻找/yyyy-你-屠洪纲.ogg" , 1 } ,
	{ "yyyy-卜卦" , "音乐待寻找/yyyy-卜卦.ogg" , 1 } ,
	{ "yyyy-君が好きだと叫びたい" , "音乐待寻找/yyyy-君が好きだと叫びたい.ogg" , 1 } ,
	{ "yyyy-君じゃなきゃダメみたい" , "音乐待寻找/yyyy-君じゃなきゃダメみたい.ogg" , 1 } ,
	{ "yyyy-咏春-七朵" , "音乐待寻找/yyyy-咏春-七朵.ogg" , 1 } ,
	{ "yyyy-在下坂本op-カスタマイZ-COOLEST" , "音乐待寻找/yyyy-在下坂本op-カスタマイZ-COOLEST.ogg" , 1 } ,
	{ "yyyy-家园《闯关东》主题曲" , "音乐待寻找/yyyy-家园《闯关东》主题曲.ogg" , 1 } ,
	{ "yyyy-小埋ED-ひだまりデイズ" , "音乐待寻找/yyyy-小埋ED-ひだまりデイズ.ogg" , 1 } ,
	{ "yyyy-小埋OP-かくしん的☆めたまるふぉ～ぜっ！" , "音乐待寻找/yyyy-小埋OP-かくしん的☆めたまるふぉ～ぜっ！.ogg" , 1 } ,
	{ "yyyy-朋友的酒" , "音乐待寻找/yyyy-朋友的酒.ogg" , 1 } ,
	{ "yyyy-甩葱歌（初音未来主题曲）" , "音乐待寻找/yyyy-甩葱歌（初音未来主题曲）.ogg" , 1 } ,
	{ "yyyy-神武女儿国-七朵" , "音乐待寻找/yyyy-神武女儿国-七朵.ogg" , 1 } ,
	{ "yyyy-落花情" , "音乐待寻找/yyyy-落花情.ogg" , 1 } ,
	{ "ワルキューレ - いけないボーダーライン" , "音乐待寻找/ワルキューレ - いけないボーダーライン.ogg" , 1 } ,
	{ "Aiobahn,YUC'e - 永久の宴" , "音乐播放列表/Aiobahn,YUC'e - 永久の宴.ogg" , 1 } ,
	{ "AKINO - 海色" , "音乐播放列表/AKINO - 海色.ogg" , 1 } ,
	{ "Alan Walker - Fade" , "音乐播放列表/Alan Walker - Fade.ogg" , 1 } ,
	{ "ARM,miko - 魔理沙は大変なものを盗んでいきました" , "音乐播放列表/ARM,miko - 魔理沙は大変なものを盗んでいきました.ogg" , 1 } ,
	{ "Asher Monroe - Here With You" , "音乐播放列表/Asher Monroe - Here With You.ogg" , 1 } ,
	{ "Avril Lavigne - Girlfriend" , "音乐播放列表/Avril Lavigne - Girlfriend.ogg" , 1 } ,
	{ "azusa - 真夏のフォトグラフ" , "音乐播放列表/azusa - 真夏のフォトグラフ.ogg" , 1 } ,
	{ "Bag Raiders - Shooting Stars (Instrumental)" , "音乐播放列表/Bag Raiders - Shooting Stars (Instrumental).ogg" , 1 } ,
	{ "ClariS - コネクト" , "音乐播放列表/ClariS - コネクト.ogg" , 1 } ,
	{ "CY8ER - HANNARI" , "音乐播放列表/CY8ER - HANNARI.ogg" , 1 } ,
	{ "Cyua - Blumenkranz" , "音乐播放列表/Cyua - Blumenkranz.ogg" , 1 } ,
	{ "Diana Boncheva - Purple Passion" , "音乐播放列表/Diana Boncheva - Purple Passion.ogg" , 1 } ,
	{ "Duca - ISI" , "音乐播放列表/Duca - ISI.ogg" , 1 } ,
	{ "Dungeon and Fighter - 王的遗迹 - sc_b03" , "音乐播放列表/Dungeon and Fighter - 王的遗迹 - sc_b03.ogg" , 1 } ,
	{ "Ed Sheeran - Shape of You" , "音乐播放列表/Ed Sheeran - Shape of You.ogg" , 1 } ,
	{ "EDOGA-SULLIVAN - WONDERFUL WONDER" , "音乐播放列表/EDOGA-SULLIVAN - WONDERFUL WONDER.ogg" , 1 } ,
	{ "F.I.R. - 千年之恋" , "音乐播放列表/F.I.R. - 千年之恋.ogg" , 1 } ,
	{ "Fall Out Boy - Immortals" , "音乐播放列表/Fall Out Boy - Immortals.ogg" , 1 } ,
	{ "Fort Minor,Styles of Beyond - Remember The Name" , "音乐播放列表/Fort Minor,Styles of Beyond - Remember The Name.ogg" , 1 } ,
	{ "fripSide - eternal reality" , "音乐播放列表/fripSide - eternal reality.ogg" , 1 } ,
	{ "fripSide - only my railgun" , "音乐播放列表/fripSide - only my railgun.ogg" , 1 } ,
	{ "GALA - 追梦赤子心" , "音乐播放列表/GALA - 追梦赤子心.ogg" , 1 } ,
	{ "GARNiDELiA - 極楽浄土" , "音乐播放列表/GARNiDELiA - 極楽浄土.ogg" , 1 } ,
	{ "Halozy,長尾ちえみ - Kiss & Crazy" , "音乐播放列表/Halozy,長尾ちえみ - Kiss & Crazy.ogg" , 1 } ,
	{ "Hawk Nelson - Sold Out" , "音乐播放列表/Hawk Nelson - Sold Out.ogg" , 1 } ,
	{ "HoneyWorks,雨宮天 - 可愛くなりたい" , "音乐播放列表/HoneyWorks,雨宮天 - 可愛くなりたい.ogg" , 1 } ,
	{ "IOSYS - エンドレス・てゐマパーク" , "音乐播放列表/IOSYS - エンドレス・てゐマパーク.ogg" , 1 } ,
	{ "Juanes - La Camisa Negra" , "音乐播放列表/Juanes - La Camisa Negra.ogg" , 1 } ,
	{ "Kalafina - Magia" , "音乐播放列表/Kalafina - Magia.ogg" , 1 } ,
	{ "Kana - ハンマーを電波ソングにしてみた" , "音乐播放列表/Kana - ハンマーを電波ソングにしてみた.ogg" , 1 } ,
	{ "Katy Perry - I Kissed A Girl" , "音乐播放列表/Katy Perry - I Kissed A Girl.ogg" , 1 } ,
	{ "Lady Gaga - Poker Face" , "音乐播放列表/Lady Gaga - Poker Face.ogg" , 1 } ,
	{ "Linkin Park - In The End" , "音乐播放列表/Linkin Park - In The End.ogg" , 1 } ,
	{ "lol - sync" , "音乐播放列表/lol - sync.ogg" , 1 } ,
	{ "Maksim Mrvica - Croatian Rhapsody" , "音乐播放列表/Maksim Mrvica - Croatian Rhapsody.ogg" , 1 } ,
	{ "MANYO - 侵食" , "音乐播放列表/MANYO - 侵食.ogg" , 1 } ,
	{ "maoto - 向日葵の咲く場所 ～daydream flowers～" , "音乐播放列表/maoto - 向日葵の咲く場所 ～daydream flowers～.ogg" , 1 } ,
	{ "MARiA - ブリキノダンス" , "音乐播放列表/MARiA - ブリキノダンス.ogg" , 1 } ,
	{ "MYTH & ROID - VORACITY" , "音乐播放列表/MYTH & ROID - VORACITY.ogg" , 1 } ,
	{ "Nightwish - I Want My Tears Back" , "音乐播放列表/Nightwish - I Want My Tears Back.ogg" , 1 } ,
	{ "OMFG - Ice Cream" , "音乐播放列表/OMFG - Ice Cream.ogg" , 1 } ,
	{ "One Direction - What Makes You Beautiful" , "音乐播放列表/One Direction - What Makes You Beautiful.ogg" , 1 } ,
	{ "ORESAMA - Gimmme!" , "音乐播放列表/ORESAMA - Gimmme!.ogg" , 1 } ,
	{ "petit milady - 恋はみるくてぃ" , "音乐播放列表/petit milady - 恋はみるくてぃ.ogg" , 1 } ,
	{ "PSY - Gentleman" , "音乐播放列表/PSY - Gentleman.ogg" , 1 } ,
	{ "ROUND TABLE - Let Me Be With You" , "音乐播放列表/ROUND TABLE - Let Me Be With You.ogg" , 1 } ,
	{ "Sensitive Heart - 千年幻想郷 ~ History of the Moon" , "音乐播放列表/Sensitive Heart - 千年幻想郷 ~ History of the Moon.ogg" , 1 } ,
	{ "SHAKING PINK - Honey Bunny My Love" , "音乐播放列表/SHAKING PINK - Honey Bunny My Love.ogg" , 1 } ,
	{ "Stratovarius - Eagle Heart" , "音乐播放列表/Stratovarius - Eagle Heart.ogg" , 1 } ,
	{ "Stratovarius - Forever" , "音乐播放列表/Stratovarius - Forever.ogg" , 1 } ,
	{ "sweet ARMS - Trust in you" , "音乐播放列表/sweet ARMS - Trust in you.ogg" , 1 } ,
	{ "sweet ARMS - デート・ア・ライブ" , "音乐播放列表/sweet ARMS - デート・ア・ライブ.ogg" , 1 } ,
	{ "TAMUSIC - ネクロファンタジア" , "音乐播放列表/TAMUSIC - ネクロファンタジア.ogg" , 1 } ,
	{ "TheFatRat - Unity" , "音乐播放列表/TheFatRat - Unity.ogg" , 1 } ,
	{ "TheFatRat,Laura Brehm - Monody (Radio Edit)" , "音乐播放列表/TheFatRat,Laura Brehm - Monody (Radio Edit).ogg" , 1 } ,
	{ "TRUSTRICK - FLYING FAFNIR" , "音乐播放列表/TRUSTRICK - FLYING FAFNIR.ogg" , 1 } ,
	{ "Two Steps From Hell - Victory" , "音乐播放列表/Two Steps From Hell - Victory.ogg" , 1 } ,
	{ "Yunomi - ハッピーライフ" , "音乐播放列表/Yunomi - ハッピーライフ.ogg" , 1 } ,
	{ "Yunomi - ロボティックガール" , "音乐播放列表/Yunomi - ロボティックガール.ogg" , 1 } ,
	{ "Yunomi - 神様の渦" , "音乐播放列表/Yunomi - 神様の渦.ogg" , 1 } ,
	{ "Yunomi,nicamoq - 東京シュノーケル" , "音乐播放列表/Yunomi,nicamoq - 東京シュノーケル.ogg" , 1 } ,
	{ "Yunomi,桃箱,miko - 曖昧トリップ" , "音乐播放列表/Yunomi,桃箱,miko - 曖昧トリップ.ogg" , 1 } ,
	{ "Zayde Wølf - Born Ready" , "音乐播放列表/Zayde Wølf - Born Ready.ogg" , 1 } ,
	{ "μ's - 僕らは今のなかで (TVサイズ)" , "音乐播放列表/μ's - 僕らは今のなかで (TVサイズ).ogg" , 1 } ,
	{ "ここなつ - ヒミツダイヤル" , "音乐播放列表/ここなつ - ヒミツダイヤル.ogg" , 1 } ,
	{ "たま,ｙｔｒ - とある瀟洒な従者の物語 (feat. ｙｔｒ)" , "音乐播放列表/たま,ｙｔｒ - とある瀟洒な従者の物語 (feat. ｙｔｒ).ogg" , 1 } ,
	{ "のみこ,Masayoshi Minoshima - Bad Apple!!" , "音乐播放列表/のみこ,Masayoshi Minoshima - Bad Apple!!.ogg" , 1 } ,
	{ "コミネリサ - Resuscitated Hope" , "音乐播放列表/コミネリサ - Resuscitated Hope.ogg" , 1 } ,
	{ "コミネリサ - unity" , "音乐播放列表/コミネリサ - unity.ogg" , 1 } ,
	{ "ファイルーズあい,石川界人 - お願いマッスル" , "音乐播放列表/ファイルーズあい,石川界人 - お願いマッスル.ogg" , 1 } ,
	{ "フランシュシュ - 徒花ネクロマンシー" , "音乐播放列表/フランシュシュ - 徒花ネクロマンシー.ogg" , 1 } ,
	{ "ベリーグッドマン - Pain, Pain Go Away" , "音乐播放列表/ベリーグッドマン - Pain, Pain Go Away.ogg" , 1 } ,
	{ "ペットな彼女たち - 君が夢を連れてきた" , "音乐播放列表/ペットな彼女たち - 君が夢を連れてきた.ogg" , 1 } ,
	{ "ワルキューレ - いけないボーダーライン" , "音乐播放列表/ワルキューレ - いけないボーダーライン.ogg" , 1 } ,
	{ "上坂すみれ - 七つの海よりキミの海" , "音乐播放列表/上坂すみれ - 七つの海よりキミの海.ogg" , 1 } ,
	{ "上海アリス幻樂団 - 科学世紀の少年少女" , "音乐播放列表/上海アリス幻樂団 - 科学世紀の少年少女.ogg" , 1 } ,
	{ "中村千尋 - カサネテク" , "音乐播放列表/中村千尋 - カサネテク.ogg" , 1 } ,
	{ "久保ユリカ,水瀬いのり - More One Night" , "音乐播放列表/久保ユリカ,水瀬いのり - More One Night.ogg" , 1 } ,
	{ "久保ユリカ,水瀬いのり - 雨だれの歌" , "音乐播放列表/久保ユリカ,水瀬いのり - 雨だれの歌.ogg" , 1 } ,
	{ "五彩呼伦贝尔儿童合唱团 - 梦中的额吉" , "音乐播放列表/五彩呼伦贝尔儿童合唱团 - 梦中的额吉.ogg" , 1 } ,
	{ "井口裕香 - 白金ディスコ" , "音乐播放列表/井口裕香 - 白金ディスコ.ogg" , 1 } ,
	{ "伊瀬茉莉也,佐倉綾音,井上麻里奈 - MOST以上の＂MOSTEST＂(ver.1)" , "音乐播放列表/伊瀬茉莉也,佐倉綾音,井上麻里奈 - MOST以上の＂MOSTEST＂(ver.1).ogg" , 1 } ,
	{ "伊藤サチコ - いつも何度でも" , "音乐播放列表/伊藤サチコ - いつも何度でも.ogg" , 1 } ,
	{ "佐々木 李子 - Good Night" , "音乐播放列表/佐々木 李子 - Good Night.ogg" , 1 } ,
	{ "冰淇 - 不了了之" , "音乐播放列表/冰淇 - 不了了之.ogg" , 1 } ,
	{ "凤凰传奇 - 我们的歌谣" , "音乐播放列表/凤凰传奇 - 我们的歌谣.ogg" , 1 } ,
	{ "分島花音 - RIGHT LIGHT RISE" , "音乐播放列表/分島花音 - RIGHT LIGHT RISE.ogg" , 1 } ,
	{ "初音ミク,40mP - 恋愛裁判" , "音乐播放列表/初音ミク,40mP - 恋愛裁判.ogg" , 1 } ,
	{ "初音ミク,doriko - ロミオとシンデレラ" , "音乐播放列表/初音ミク,doriko - ロミオとシンデレラ.ogg" , 1 } ,
	{ "初音ミク,鏡音リン,GUMI - 神のまにまに" , "音乐播放列表/初音ミク,鏡音リン,GUMI - 神のまにまに.ogg" , 1 } ,
	{ "原田ひとみ,茅野愛衣,小倉唯 - 回レ! 雪月花" , "音乐播放列表/原田ひとみ,茅野愛衣,小倉唯 - 回レ! 雪月花.ogg" , 1 } ,
	{ "吉木りさ - Destin Histoire" , "音乐播放列表/吉木りさ - Destin Histoire.ogg" , 1 } ,
	{ "周志宏 - 风弄月影摇" , "音乐播放列表/周志宏 - 风弄月影摇.ogg" , 1 } ,
	{ "和田光司 - Butter-Fly" , "音乐播放列表/和田光司 - Butter-Fly.ogg" , 1 } ,
	{ "喜多村英梨,野中藍 - and I'm home" , "音乐播放列表/喜多村英梨,野中藍 - and I'm home.ogg" , 1 } ,
	{ "富田美憂,小林裕介,間島淳司 - イこうぜ☆パラダイス" , "音乐播放列表/富田美憂,小林裕介,間島淳司 - イこうぜ☆パラダイス.ogg" , 1 } ,
	{ "小原好美,鬼頭明里 - 町かどタンジェント" , "音乐播放列表/小原好美,鬼頭明里 - 町かどタンジェント.ogg" , 1 } ,
	{ "小原好美,鬼頭明里,高橋未奈美 - よいまちカンターレ" , "音乐播放列表/小原好美,鬼頭明里,高橋未奈美 - よいまちカンターレ.ogg" , 1 } ,
	{ "小潘潘（潘柚彤）,小峰峰（陈峰） - 学猫叫" , "音乐播放列表/小潘潘（潘柚彤）,小峰峰（陈峰） - 学猫叫.ogg" , 1 } ,
	{ "展展与罗罗 - 沙漠骆驼" , "音乐播放列表/展展与罗罗 - 沙漠骆驼.ogg" , 1 } ,
	{ "山下七海 - Hazy Lazy Doll" , "音乐播放列表/山下七海 - Hazy Lazy Doll.ogg" , 1 } ,
	{ "川嶋あい - それが大事" , "音乐播放列表/川嶋あい - それが大事.ogg" , 1 } ,
	{ "川田まみ - Prophecy" , "音乐播放列表/川田まみ - Prophecy.ogg" , 1 } ,
	{ "川田まみ - PSI-missing" , "音乐播放列表/川田まみ - PSI-missing.ogg" , 1 } ,
	{ "川田まみ - 緋色の空" , "音乐播放列表/川田まみ - 緋色の空.ogg" , 1 } ,
	{ "平野綾 - God knows" , "音乐播放列表/平野綾 - God knows.ogg" , 1 } ,
	{ "幽閉サテライト - 大地に咲く旋律" , "音乐播放列表/幽閉サテライト - 大地に咲く旋律.ogg" , 1 } ,
	{ "张晓璐MOMO - 看得最远的地方" , "音乐播放列表/张晓璐MOMO - 看得最远的地方.ogg" , 1 } ,
	{ "张杰 - 天下" , "音乐播放列表/张杰 - 天下.ogg" , 1 } ,
	{ "张杰 - 着魔" , "音乐播放列表/张杰 - 着魔.ogg" , 1 } ,
	{ "彩音 - Orange" , "音乐播放列表/彩音 - Orange.ogg" , 1 } ,
	{ "後ろから這いより隊G - 太陽曰く燃えよカオス" , "音乐播放列表/後ろから這いより隊G - 太陽曰く燃えよカオス.ogg" , 1 } ,
	{ "後ろから這いより隊G - 嫌いなワケLychee" , "音乐播放列表/後ろから這いより隊G - 嫌いなワケLychee.ogg" , 1 } ,
	{ "後ろから這いより隊G - 恋は渾沌の隷也" , "音乐播放列表/後ろから這いより隊G - 恋は渾沌の隷也.ogg" , 1 } ,
	{ "悠木碧 - また あした" , "音乐播放列表/悠木碧 - また あした.ogg" , 1 } ,
	{ "愛殺寶貝 - ふたりのきもちのほんとのひみつ" , "音乐播放列表/愛殺寶貝 - ふたりのきもちのほんとのひみつ.ogg" , 1 } ,
	{ "放課後ティータイム - NO,Thank You!" , "音乐播放列表/放課後ティータイム - NO,Thank You!.ogg" , 1 } ,
	{ "日高里菜,沼倉愛美 - Ray of bullet (イリス・フレイア& 物部深月 ver.)" , "音乐播放列表/日高里菜,沼倉愛美 - Ray of bullet (イリス・フレイア& 物部深月 ver.).ogg" , 1 } ,
	{ "時音(TOKINE) - 願いを呼ぶ季節" , "音乐播放列表/時音(TOKINE) - 願いを呼ぶ季節.ogg" , 1 } ,
	{ "曲婉婷 - 我的歌声里" , "音乐播放列表/曲婉婷 - 我的歌声里.ogg" , 1 } ,
	{ "朱铭捷 - 曾经最美" , "音乐播放列表/朱铭捷 - 曾经最美.ogg" , 1 } ,
	{ "李荣浩 - 喜剧之王" , "音乐播放列表/李荣浩 - 喜剧之王.ogg" , 1 } ,
	{ "李袁杰 - 离人愁" , "音乐播放列表/李袁杰 - 离人愁.ogg" , 1 } ,
	{ "杨幂 - 爱的供养" , "音乐播放列表/杨幂 - 爱的供养.ogg" , 1 } ,
	{ "松来未佑,柚木凉香 - Sister,Friend,Lover" , "音乐播放列表/松来未佑,柚木凉香 - Sister,Friend,Lover.ogg" , 1 } ,
	{ "林俊杰 - 黑武士" , "音乐播放列表/林俊杰 - 黑武士.ogg" , 1 } ,
	{ "桜高軽音部 - Cagayake! GIRLS" , "音乐播放列表/桜高軽音部 - Cagayake! GIRLS.ogg" , 1 } ,
	{ "梦璟SAYA - 崩坏世界の歌姬" , "音乐播放列表/梦璟SAYA - 崩坏世界の歌姬.ogg" , 1 } ,
	{ "梶浦由記 - Decretum" , "音乐播放列表/梶浦由記 - Decretum.ogg" , 1 } ,
	{ "梶浦由記 - Postmeridie" , "音乐播放列表/梶浦由記 - Postmeridie.ogg" , 1 } ,
	{ "梶浦由記 - Pugna cum maga" , "音乐播放列表/梶浦由記 - Pugna cum maga.ogg" , 1 } ,
	{ "梶浦由記 - Salve, terrae magicae" , "音乐播放列表/梶浦由記 - Salve, terrae magicae.ogg" , 1 } ,
	{ "梶浦由記 - Sis puella magica!" , "音乐播放列表/梶浦由記 - Sis puella magica!.ogg" , 1 } ,
	{ "森永真由美 - 月に叢雲華に風" , "音乐播放列表/森永真由美 - 月に叢雲華に風.ogg" , 1 } ,
	{ "森永真由美 - 泡沫、哀のまほろば" , "音乐播放列表/森永真由美 - 泡沫、哀のまほろば.ogg" , 1 } ,
	{ "森永真由美 - 色は匂へど 散りぬるを -Full Version-" , "音乐播放列表/森永真由美 - 色は匂へど 散りぬるを -Full Version-.ogg" , 1 } ,
	{ "森永真由美 - 華鳥風月(with senya) ＜幻想万華鏡 花の異変の章 OP主題歌＞" , "音乐播放列表/森永真由美 - 華鳥風月(with senya) ＜幻想万華鏡 花の異変の章 OP主題歌＞.ogg" , 1 } ,
	{ "榊原ゆい - 聖剣なんていらない" , "音乐播放列表/榊原ゆい - 聖剣なんていらない.ogg" , 1 } ,
	{ "水瀬いのり - 快眠! 安眠! スヤリスト生活" , "音乐播放列表/水瀬いのり - 快眠! 安眠! スヤリスト生活.ogg" , 1 } ,
	{ "水瀬いのり,久保ユリカ - 動く、動く" , "音乐播放列表/水瀬いのり,久保ユリカ - 動く、動く.ogg" , 1 } ,
	{ "沼倉愛美,白石晴香 - ときめき☆くらいまっくす" , "音乐播放列表/沼倉愛美,白石晴香 - ときめき☆くらいまっくす.ogg" , 1 } ,
	{ "泡泡 - 八重桜" , "音乐播放列表/泡泡 - 八重桜.ogg" , 1 } ,
	{ "浜崎あゆみ - MY ALL" , "音乐播放列表/浜崎あゆみ - MY ALL.ogg" , 1 } ,
	{ "湘南乃風 - Grand Blue" , "音乐播放列表/湘南乃風 - Grand Blue.ogg" , 1 } ,
	{ "火箭少女101 - 卡路里" , "音乐播放列表/火箭少女101 - 卡路里.ogg" , 1 } ,
	{ "田村ゆかり - Fantastic future" , "音乐播放列表/田村ゆかり - Fantastic future.ogg" , 1 } ,
	{ "田村ゆかり - W：Wonder tale" , "音乐播放列表/田村ゆかり - W：Wonder tale.ogg" , 1 } ,
	{ "竹達彩奈 - 恋のEveryDay☆HappyDay(フルサイズ)" , "音乐播放列表/竹達彩奈 - 恋のEveryDay☆HappyDay(フルサイズ).ogg" , 1 } ,
	{ "米津玄師 - Lemon" , "音乐播放列表/米津玄師 - Lemon.ogg" , 1 } ,
	{ "罗志祥 - 狐狸精" , "音乐播放列表/罗志祥 - 狐狸精.ogg" , 1 } ,
	{ "美郷あき - DESIRE" , "音乐播放列表/美郷あき - DESIRE.ogg" , 1 } ,
	{ "群星 - Hey Oh" , "音乐播放列表/群星 - Hey Oh.ogg" , 1 } ,
	{ "花儿乐队 - 穷开心" , "音乐播放列表/花儿乐队 - 穷开心.ogg" , 1 } ,
	{ "花澤香菜 - 恋愛サーキュレーション" , "音乐播放列表/花澤香菜 - 恋愛サーキュレーション.ogg" , 1 } ,
	{ "花粥,王胜娚 - 出山" , "音乐播放列表/花粥,王胜娚 - 出山.ogg" , 1 } ,
	{ "芹澤優,立花理香,桑原由気 - イチズレシピ庶民部Ver" , "音乐播放列表/芹澤優,立花理香,桑原由気 - イチズレシピ庶民部Ver.ogg" , 1 } ,
	{ "茅野愛衣,戸松遥,早見沙織 - secret base ~君がくれたもの~ (10 years after Ver.)" , "音乐播放列表/茅野愛衣,戸松遥,早見沙織 - secret base ~君がくれたもの~ (10 years after Ver.).ogg" , 1 } ,
	{ "萧敬腾 - 王妃" , "音乐播放列表/萧敬腾 - 王妃.ogg" , 1 } ,
	{ "蒋雪儿 - 爱河" , "音乐播放列表/蒋雪儿 - 爱河.ogg" , 1 } ,
	{ "蔡依林 - 日不落" , "音乐播放列表/蔡依林 - 日不落.ogg" , 1 } ,
	{ "西沢幸奏 - 吹雪" , "音乐播放列表/西沢幸奏 - 吹雪.ogg" , 1 } ,
	{ "许嵩 - 断桥残雪" , "音乐播放列表/许嵩 - 断桥残雪.ogg" , 1 } ,
	{ "许嵩,黄龄 - 惊鸿一面" , "音乐播放列表/许嵩,黄龄 - 惊鸿一面.ogg" , 1 } ,
	{ "豊崎愛生,日笠陽子,佐藤聡美 - 天使にふれたよ!" , "音乐播放列表/豊崎愛生,日笠陽子,佐藤聡美 - 天使にふれたよ!.ogg" , 1 } ,
	{ "赤﨑千夏,田村ゆかり,金元寿子 - Girlish Lover" , "音乐播放列表/赤﨑千夏,田村ゆかり,金元寿子 - Girlish Lover.ogg" , 1 } ,
	{ "鈴木愛奈 - 神保町哀歌" , "音乐播放列表/鈴木愛奈 - 神保町哀歌.ogg" , 1 } ,
	{ "鈴木雅之,伊原六花 - ラブ・ドラマティック" , "音乐播放列表/鈴木雅之,伊原六花 - ラブ・ドラマティック.ogg" , 1 } ,
	{ "鈴木雅之,鈴木愛理 - Daddy ! Daddy ! Do !" , "音乐播放列表/鈴木雅之,鈴木愛理 - Daddy ! Daddy ! Do !.ogg" , 1 } ,
	{ "鏡音リン,sasaki - 炉心融解" , "音乐播放列表/鏡音リン,sasaki - 炉心融解.ogg" , 1 } ,
	{ "银临,Aki阿杰 - 牵丝戏" , "音乐播放列表/银临,Aki阿杰 - 牵丝戏.ogg" , 1 } ,
	{ "青山テルマ - そばにいるね" , "音乐播放列表/青山テルマ - そばにいるね.ogg" , 1 } ,
	{ "韩磊 - 向天再借五百年" , "音乐播放列表/韩磊 - 向天再借五百年.ogg" , 1 } ,
	{ "高梨康治 - 儀礼" , "音乐播放列表/高梨康治 - 儀礼.ogg" , 1 } ,
	{ "高耀太 - 불꽃" , "音乐播放列表/高耀太 - 불꽃.ogg" , 1 }
}